sudo: required
language: generic

services:
  - docker
before_install:
  - docker-compose -f docker-compose-dev.yml up
script:
  - docker run --rm -e CI=true liuminwjh/frontend-test npm run test -- --coverage


