sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t liuminwjh/Docker -f Dockerfile.dev .

script:
  - docker run -e CI=true -v $PWD:/app -w /app liuminwjh/Docker sh -c "npm install && npm run test --coverage"

