sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t liuminwjh/frontend-test -f Dockerfile.dev .

script:
  - docker run -e CI=true liuminwjh/frontend-test npm run test --coverage

